
#ifndef __RPC_ITEM_H__
#define __RPC_ITEM_H__

typedef enum {
	RPC_GENERAL_ITEM_START = 0,
	RPC_GENERAL_ITEM_0 = RPC_GENERAL_ITEM_START,
	RPC_GENERAL_ITEM_1,
	RPC_GENERAL_ITEM_2,
	RPC_GENERAL_ITEM_3,
	RPC_GENERAL_ITEM_4,
	RPC_GENERAL_ITEM_5,
	RPC_GENERAL_ITEM_6,
	RPC_GENERAL_ITEM_7,
	RPC_GENERAL_ITEM_MAX
}t_rpc_item;

typedef void (*t_fp_callback)(t_rpc_item item);

#endif
